Add error check

diff --git a/Invisux b/Invisux
--- a/Invisux
+++ b/Invisux
@@ -37,7 +37,6 @@ BOLD="\e[1m"
 RESET="\e[0m"
 
 # Privacy
-
 privacy_menu() {
     echo
     gum_privacy_menu=$(gum choose "Return" "Exit")
@@ -96,14 +95,14 @@ generate-passwd() {
 
     if [[ ! "$length" =~ ^[0-9]+$ ]]; then
         echo "Invalid input for lenght"
-        return 0
+        return 3
     fi
 
     if [ "$length" -ge 7 ] && [ "$length" -le 129 ]; then
         echo "You selected $length as your lenght size"
     else
         echo "You selected a lenght not supported"
-        return 0
+        return 4
     fi
 
     local pass_alnum
@@ -128,10 +127,16 @@ generate-passwd() {
     entropy_full=$(awk  "BEGIN { printf \"%d\", $length * 6.554 }")
 
     echo -e "[i] Estimated entropy — alphanumeric: ~${entropy_alnum} bits  |  with symbols: ~${entropy_full} bits${RESET}"
+
+    status=$?
+    error_check
 }
 
 check_ports() {
     netstat -tuln
+
+    status=$?
+    error_check
 }
 
 audit-system() {
@@ -141,6 +146,9 @@ audit-system() {
     
     echo "Running tool: "
     sudo lynis audit system
+
+    status=$?
+    error_check
 }
 emoty_trash() {
     TRASH_FILES="$HOME/.local/share/Trash/files"
@@ -175,7 +183,7 @@ emoty_trash() {
         animation_end
     else
         echo "Cancelled"
-        return 0
+        return 6
     fi
 
     local remaining
@@ -185,8 +193,11 @@ emoty_trash() {
         echo "Succefully emptied"
     else
         echo "Some items may remain, check manually"
-        return 0
+        return 1
     fi
+
+    status=$?
+    error_check
 }
 
 delete-file() {
@@ -196,8 +207,17 @@ delete-file() {
 
     if [[ "$file" == "no file selected" ]]; then
         echo "No file was selected"
-        return 0
+        return 5
     fi
+
+    echo "Are you sure to remove $file?"
+    confirm=$(gum choose yes no)
+
+    case $confirm in
+        no)
+            return 6
+            ;;
+    esac
 
     animation_begin
 
@@ -206,6 +226,9 @@ delete-file() {
     shred -u $file
 
     animation_end
+
+    status=$?
+    error_check
 }
 
 remove_metadata() {
@@ -214,10 +237,13 @@ remove_metadata() {
 
     if [[ "$file" == "no file selected" ]]; then
         echo "No file was selected"
-        return 0
+        return 5
     fi
 
     gum confirm "Edit $file?" && exiftool -all= $file
+
+    status=$?
+    error_check
 }
 
 update-apps() {
@@ -228,7 +254,7 @@ update-apps() {
 
     case $confirm in
         no)
-            return 0
+            return 6
             ;;
     esac
 
@@ -261,10 +287,12 @@ update-apps() {
                 ;;
         esac
     done <<< "$options"
+
+    status=$?
+    error_check
 }
 
 # Encryption
-
 encryption_menu() {
     echo
     gum_encryption_menu=$(gum choose Hash Explainer General-keys AES GPG Return Exit)
@@ -321,6 +349,9 @@ hash-passwd() {
     echo 
     echo "Your hashed password is: $output"
     echo "Hashed with: $protocol"
+
+    status=$?
+    error_check
 }
 explainer_encryption() {
     cat << EOF
@@ -382,6 +413,9 @@ keys() {
         return 0
         ;;
     esac
+
+    status=$?
+    error_check
 }
 
 aes_menu() {
@@ -439,6 +473,7 @@ aes_encrypt() {
             return 0
             ;;
     esac
+
 }
 
 encrypt_128() {
@@ -451,7 +486,7 @@ encrypt_128() {
 
         if [[ "$file" == "no file selected" ]]; then
             echo "No file was selected"
-            return 0
+            return 5
         fi
         
         read -p "Enter file to write to (no extension added):    " output_file
@@ -476,7 +511,7 @@ encrypt_128() {
 
         if [[ -z "$text" ]]; then
             echo "No input provided" >&2
-            return 0
+            return 5
         fi
 
         printf "%s" "$text" | openssl enc -aes-128-cbc -pbkdf2 -iter 100000 -salt -a
@@ -489,6 +524,9 @@ encrypt_128() {
             return 0
             ;;
     esac
+
+    status=$?
+    error_check
 }
 
 encrypt_256() {
@@ -501,7 +539,7 @@ encrypt_256() {
 
         if [[ "$file" == "no file selected" ]]; then
             echo "No file was selected"
-            return 0
+            return 5
         fi
 
         read -p "Enter file to write to (no extension added):    " output_file
@@ -526,7 +564,7 @@ encrypt_256() {
 
         if [[ -z "$text" ]]; then
             echo "No input provided" >&2
-            return 0
+            return 5
         fi
 
         printf "%s" "$text" | openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -salt -a
@@ -538,6 +576,9 @@ encrypt_256() {
             return 0
             ;;
     esac
+
+    status=$?
+    error_check
 }
 
 decrypt_128() {
@@ -550,7 +591,7 @@ decrypt_128() {
 
         if [[ "$file" == "no file selected" ]]; then
             echo "No file was selected"
-            return 0
+            return 5
         fi
 
         read -p "Enter file to write to (no extension added):    " output_file
@@ -575,7 +616,7 @@ decrypt_128() {
 
         if [[ -z "$text" ]]; then
             echo "No input provided" >&2
-            return 0
+            return 5
         fi
 
         printf "%s" "$text" | openssl enc -aes-128-cbc -d -pbkdf2 -iter 100000 -a
@@ -587,6 +628,9 @@ decrypt_128() {
             return 0
             ;;
     esac
+
+    status=$?
+    error_check
 }
 
 decrypt_256() {
@@ -599,7 +643,7 @@ decrypt_256() {
 
         if [[ "$file" == "no file selected" ]]; then
             echo "No file was selected"
-            return 0
+            return 5
         fi
 
         read -p "Enter file to write to (no extension added):    " output_file
@@ -624,7 +668,7 @@ decrypt_256() {
 
         if [[ -z "$text" ]]; then
             echo "No input provided" >&2
-            return 0
+            return 5
         fi
 
         printf "%s" "$text" | openssl enc -aes-256-cbc -d -pbkdf2 -iter 100000 -a
@@ -636,6 +680,9 @@ decrypt_256() {
             return 0
             ;;
     esac
+
+    status=$?
+    error_check
 }
 
 gpg_menu() {
@@ -674,6 +721,9 @@ gpg_menu() {
 
 generate-key() {
     gpg --gen-key
+
+    status=$?
+    error_check
 } 
 
 delete-key() {
@@ -690,6 +740,9 @@ delete-key() {
             gum confirm "Delete key for: $username?" && gpg --delete-secret-key $username
         ;;
     esac
+
+    status=$?
+    error_check
 }
 
 import-key() {
@@ -697,6 +750,9 @@ import-key() {
     file=$(gum file)
 
     gpg --import $file
+
+    status=$?
+    error_check
 } 
 
 export-key() {
@@ -704,6 +760,9 @@ export-key() {
     read -p "Enter file to write to (no extension added):    " file
 
     gpg --export -a $username $file.key
+
+    status=$?
+    error_check
 } 
 
 list-keys() {
@@ -711,6 +770,9 @@ list-keys() {
     gpg --list-keys
     echo "Secret:   "
     gpg --list-secret-keys
+
+    status=$?
+    error_check
 } 
 
 sign() {
@@ -718,6 +780,9 @@ sign() {
     file=$(gum file)
 
     gpg --sign $file
+
+    status=$?
+    error_check
 }
 
 verify() {
@@ -725,6 +790,9 @@ verify() {
     file=$(gum file)
 
 	gpg --verify $file
+
+    status=$?
+    error_check
 }
 
 help () {
@@ -757,6 +825,9 @@ EOF
     echo
 
     curl https://codeberg.org/JasperC/Invisux/raw/branch/main/version
+
+    status=$?
+    error_check
 }
 
 license_menu() {
@@ -783,6 +854,9 @@ license_menu() {
 }
 full-license() {
     curl https://codeberg.org/JasperC/Invisux/raw/branch/main/LICENSE
+
+    status=$?
+    error_check
 }
 license_overview() {
     cat << EOF
@@ -794,6 +868,52 @@ name-of-license() {
     echo "License: GNU General Public License v3"
 }
 
+# Error handling
+error_check() {
+    echo "Error status: "
+
+    case $status in
+        0)
+            echo "Succes / no error"
+        ;;
+        1)
+            echo "General/catchall error"
+        ;;
+        2)
+            echo "Misuse of shell builtin"
+        ;;
+        3)
+            echo "General: Invalid input"
+            ;;
+        4)
+            echo "Input does not meet the requirements of the input"
+            ;;
+        5)
+            echo "Empty input"
+            ;;
+        6)
+            echo "Action aborted"
+            ;;
+        126)
+            echo "Command found but not executable"
+            ;;
+        127)
+            echo "Command not found"
+            ;;
+        128)
+            echo "Invalid argument to exit"
+            ;;
+        128+N)
+            echo "Terminated by signal N"
+            ;;
+        255)
+            echo "Exit status out of range / uncaught error"
+            ;;
+        *)
+            echo "Unhandled exit status: $status" >&2
+        ;;
+    esac
+}
 # Alliases
 license() {
     full-license
